<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Movie;

class MovieSeeder extends Seeder
{
    public function run(): void
    {
        // Nonaktifkan foreign key check agar truncate tidak error
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Movie::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $movies = [
            [
                'title'        => 'Oppenheimer',
                'description'  => 'The story of J. Robert Oppenheimer and the development of the atomic bomb during World War II.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
                'rating'       => 8.9,
                'categories'   => json_encode(['Drama', 'History']),
                'release_year' => 2023,
                'views'        => 120000,
                'is_trending'  => true,
            ],
            [
                'title'        => 'Interstellar',
                'description'  => 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
                'rating'       => 9.1,
                'categories'   => json_encode(['Sci-Fi', 'Adventure']),
                'release_year' => 2014,
                'views'        => 250000,
                'is_trending'  => true,
            ],
            [
                'title'        => 'Avengers: Endgame',
                'description'  => 'The Avengers assemble once more to reverse the devastation caused by Thanos.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
                'rating'       => 8.7,
                'categories'   => json_encode(['Action', 'Adventure']),
                'release_year' => 2019,
                'views'        => 300000,
                'is_trending'  => true,
            ],
            [
                'title'        => 'The Batman',
                'description'  => 'Batman ventures into Gotham City\'s underworld when a serial killer leaves behind cryptic clues.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg',
                'rating'       => 8.3,
                'categories'   => json_encode(['Action', 'Crime']),
                'release_year' => 2022,
                'views'        => 180000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Inception',
                'description'  => 'A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
                'rating'       => 8.8,
                'categories'   => json_encode(['Sci-Fi', 'Thriller']),
                'release_year' => 2010,
                'views'        => 400000,
                'is_trending'  => true,
            ],
            [
                'title'        => 'Joker',
                'description'  => 'A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of the Joker.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/n6bUvigpRFqSwmPp1m25gM6JZhb.jpg',
                'rating'       => 8.5,
                'categories'   => json_encode(['Drama', 'Crime']),
                'release_year' => 2019,
                'views'        => 350000,
                'is_trending'  => true,
            ],
            [
                'title'        => 'Titanic',
                'description'  => 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious RMS Titanic.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/kHXEpyfl6zqn8a6YuozZUujufXf.jpg',
                'rating'       => 8.6,
                'categories'   => json_encode(['Romance', 'Drama']),
                'release_year' => 1997,
                'views'        => 500000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'The Matrix',
                'description'  => 'A computer hacker learns about the true nature of his reality and his role in the war against its controllers.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg',
                'rating'       => 8.7,
                'categories'   => json_encode(['Sci-Fi', 'Action']),
                'release_year' => 1999,
                'views'        => 450000,
                'is_trending'  => true,
            ],
            [
                'title'        => 'John Wick',
                'description'  => 'An ex-hit-man comes out of retirement to track down the gangsters that killed his dog.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/umC04Cozevu8nn3ZTIU9rNyfWHs.jpg',
                'rating'       => 8.2,
                'categories'   => json_encode(['Action', 'Thriller']),
                'release_year' => 2014,
                'views'        => 280000,
                'is_trending'  => true,
            ],
            [
                'title'        => 'Gladiator',
                'description'  => 'A Roman general is betrayed and seeks revenge as a gladiator.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/6WBIzCgmDCYrqh64yDREGeDk9d3.jpg',
                'rating'       => 8.5,
                'categories'   => json_encode(['Action', 'Drama']),
                'release_year' => 2000,
                'views'        => 220000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'The Dark Knight',
                'description'  => 'Batman faces the Joker, a criminal mastermind who plunges Gotham into chaos.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/hqkIcbrOHL86UncnHIsHVcVmzue.jpg',
                'rating'       => 9.5,
                'categories'   => json_encode(['Action', 'Crime']),
                'release_year' => 2008,
                'views'        => 600000,
                'is_trending'  => true,
            ],
            [
                'title'        => 'Parasite',
                'description'  => 'A poor family schemes to become employed by a wealthy family.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
                'rating'       => 9.2,
                'categories'   => json_encode(['Drama', 'Thriller']),
                'release_year' => 2019,
                'views'        => 310000,
                'is_trending'  => true,
            ],
            [
                'title'        => 'Dune',
                'description'  => 'A noble family becomes embroiled in a war for the desert planet Arrakis.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/d5NXSklpcvkDkHpRh4J3uerEDpl.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/eeijXm3553xvuFbkPFkDG6CLCbQ.jpg',
                'rating'       => 8.4,
                'categories'   => json_encode(['Sci-Fi', 'Adventure']),
                'release_year' => 2021,
                'views'        => 270000,
                'is_trending'  => true,
            ],
            [
                'title'        => 'Spider-Man: No Way Home',
                'description'  => 'Spider-Man seeks help from Doctor Strange but the multiverse is torn open.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
                'rating'       => 8.6,
                'categories'   => json_encode(['Action', 'Adventure']),
                'release_year' => 2021,
                'views'        => 420000,
                'is_trending'  => true,
            ],
            [
                'title'        => 'Top Gun: Maverick',
                'description'  => 'After 30 years, Maverick is still pushing the envelope as a top naval aviator.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/62HCnUTHk3KjCkZ1rFOGvFJmm7k.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/AkB2soMBMbrHnMTFl1nXTL1QHex.jpg',
                'rating'       => 8.5,
                'categories'   => json_encode(['Action', 'Drama']),
                'release_year' => 2022,
                'views'        => 390000,
                'is_trending'  => true,
            ],
            [
                'title'        => 'The Shawshank Redemption',
                'description'  => 'Two imprisoned men bond over years, finding solace and redemption through acts of decency.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
                'rating'       => 9.8,
                'categories'   => json_encode(['Drama']),
                'release_year' => 1994,
                'views'        => 700000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'The Godfather',
                'description'  => 'An aging patriarch transfers control of his clandestine empire to his reluctant son.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLeMMovrISFP.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/tmU7GeKVPlBBgBezMJDFX35yfmr.jpg',
                'rating'       => 9.7,
                'categories'   => json_encode(['Crime', 'Drama']),
                'release_year' => 1972,
                'views'        => 650000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Forrest Gump',
                'description'  => 'The life journey of Forrest Gump who witnesses several defining events in American history.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
                'rating'       => 9.3,
                'categories'   => json_encode(['Drama', 'Romance']),
                'release_year' => 1994,
                'views'        => 580000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Pulp Fiction',
                'description'  => 'The lives of two mob hitmen, a boxer, and others intertwine in a series of tales.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
                'rating'       => 9.4,
                'categories'   => json_encode(['Crime', 'Drama']),
                'release_year' => 1994,
                'views'        => 520000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'The Lion King',
                'description'  => 'A young lion prince flees his kingdom only to learn the true meaning of responsibility.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/wXsQvli6tWqja51pYxXNG1LFIGV.jpg',
                'rating'       => 8.8,
                'categories'   => json_encode(['Animation', 'Adventure']),
                'release_year' => 1994,
                'views'        => 480000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Goodfellas',
                'description'  => 'Henry Hill and his friends work their way up through the mob hierarchy.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/sw7mordbZxgITU877yTpZCud90M.jpg',
                'rating'       => 9.0,
                'categories'   => json_encode(['Crime', 'Drama']),
                'release_year' => 1990,
                'views'        => 340000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Schindler\'s List',
                'description'  => 'A businessman saves the lives of over a thousand Jews during the Holocaust.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/loRmRzQXZeqG78TqZunkcMVNnLl.jpg',
                'rating'       => 9.6,
                'categories'   => json_encode(['Drama', 'History']),
                'release_year' => 1993,
                'views'        => 410000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'The Lord of the Rings: The Return of the King',
                'description'  => 'Gandalf and Aragorn lead the World of Men against Sauron\'s army.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg',
                'rating'       => 9.5,
                'categories'   => json_encode(['Fantasy', 'Adventure']),
                'release_year' => 2003,
                'views'        => 560000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Fight Club',
                'description'  => 'An insomniac office worker and a soap salesman build a secret underground fight club.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzVPW6J.jpg',
                'rating'       => 9.3,
                'categories'   => json_encode(['Drama', 'Thriller']),
                'release_year' => 1999,
                'views'        => 490000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Whiplash',
                'description'  => 'A promising young drummer enrolls at a cut-throat music conservatory.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/6bbZ6XyvgfjhQwbplnUh1LSj1ky.jpg',
                'rating'       => 9.0,
                'categories'   => json_encode(['Drama', 'Music']),
                'release_year' => 2014,
                'views'        => 290000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'La La Land',
                'description'  => 'A jazz musician and an aspiring actress fall in love in Los Angeles.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/nadTlnTE6DdgmYsN4iWc2a2wiaB.jpg',
                'rating'       => 8.6,
                'categories'   => json_encode(['Romance', 'Music']),
                'release_year' => 2016,
                'views'        => 310000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Mad Max: Fury Road',
                'description'  => 'In a post-apocalyptic wasteland, Max teams up with a rebel warrior to flee a tyrant.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/kqjL17yufvn9OVLyXYpvtyrFfak.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/phszHPFPXpLiEoFzOiIGWKMOEO5.jpg',
                'rating'       => 8.7,
                'categories'   => json_encode(['Action', 'Adventure']),
                'release_year' => 2015,
                'views'        => 330000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Get Out',
                'description'  => 'A young African American man visits his white girlfriend\'s family estate.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/b2cGVNBxhnKVGhBTakFnFRAPiSu.jpg',
                'rating'       => 8.4,
                'categories'   => json_encode(['Horror', 'Thriller']),
                'release_year' => 2017,
                'views'        => 240000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Avengers: Infinity War',
                'description'  => 'The Avengers and allies must fight to defeat Thanos before he collects all six Infinity Stones.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg',
                'rating'       => 8.8,
                'categories'   => json_encode(['Action', 'Adventure']),
                'release_year' => 2018,
                'views'        => 460000,
                'is_trending'  => true,
            ],
            [
                'title'        => 'Blade Runner 2049',
                'description'  => 'A young blade runner discovers a long-buried secret that leads him to find Rick Deckard.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/eIi3klFf7mp3oL5EEF4mLIDs26r.jpg',
                'rating'       => 8.6,
                'categories'   => json_encode(['Sci-Fi', 'Drama']),
                'release_year' => 2017,
                'views'        => 200000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'No Country for Old Men',
                'description'  => 'Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/6d5XOczc0Hj3LBNHeg4gMxIZb6k.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/6dEFBpZH8C8OijsynkSajQT99Pb.jpg',
                'rating'       => 9.1,
                'categories'   => json_encode(['Crime', 'Drama']),
                'release_year' => 2007,
                'views'        => 280000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'The Silence of the Lambs',
                'description'  => 'A young FBI cadet seeks the help of Dr. Hannibal Lecter to catch a serial killer.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/mfwq2nMBzArzQ7Y9RKE8SKeeTkg.jpg',
                'rating'       => 9.2,
                'categories'   => json_encode(['Crime', 'Thriller']),
                'release_year' => 1991,
                'views'        => 370000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Jurassic Park',
                'description'  => 'A pragmatic paleontologist visiting an almost-completed amusement park is stranded when dinosaurs break loose.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg',
                'rating'       => 8.7,
                'categories'   => json_encode(['Adventure', 'Sci-Fi']),
                'release_year' => 1993,
                'views'        => 440000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'The Prestige',
                'description'  => 'Two stage magicians engage in a bitter rivalry and try to create the ultimate illusion.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/5MXyQfz8xUP3dIFPTubhTsbFY6N.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/j18EBjSdxHKVFIRHXcwKJaHHlV8.jpg',
                'rating'       => 9.0,
                'categories'   => json_encode(['Drama', 'Mystery']),
                'release_year' => 2006,
                'views'        => 320000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Coco',
                'description'  => 'A young boy enters the Land of the Dead to find his great-great-grandfather.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/askg3SMvhqEl4OL52YuvdtY40Yb.jpg',
                'rating'       => 8.9,
                'categories'   => json_encode(['Animation', 'Adventure']),
                'release_year' => 2017,
                'views'        => 380000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Soul',
                'description'  => 'A musician\'s soul gets separated from his body and must return before it\'s too late.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg',
                'rating'       => 8.8,
                'categories'   => json_encode(['Animation', 'Drama']),
                'release_year' => 2020,
                'views'        => 290000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Everything Everywhere All at Once',
                'description'  => 'An aging Chinese immigrant is swept up in an adventure to save the multiverse.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/sZNNsquMQzwvnSRK6cZrjJstkBo.jpg',
                'rating'       => 9.0,
                'categories'   => json_encode(['Action', 'Comedy']),
                'release_year' => 2022,
                'views'        => 260000,
                'is_trending'  => true,
            ],
            [
                'title'        => 'Tár',
                'description'  => 'The life of a world-renowned conductor unravels as she faces a reckoning for her past.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/hTP1DtLGFAmAr9AL6nJGqOBOkEa.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/4HodYsaOGXjoh3yHFI8kHfKEBjS.jpg',
                'rating'       => 8.3,
                'categories'   => json_encode(['Drama', 'Music']),
                'release_year' => 2022,
                'views'        => 150000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Guardians of the Galaxy',
                'description'  => 'A group of intergalactic criminals are forced to work together to stop a fanatical warrior.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/bHarw8xrmQeqf3t8HpuMY7zoK4x.jpg',
                'rating'       => 8.5,
                'categories'   => json_encode(['Action', 'Comedy']),
                'release_year' => 2014,
                'views'        => 410000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Black Panther',
                'description'  => 'T\'Challa returns home to Wakanda to take the throne but faces a powerful enemy.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/6ELJEzQJ3Y45HczvreToZXR0sMF.jpg',
                'rating'       => 8.4,
                'categories'   => json_encode(['Action', 'Adventure']),
                'release_year' => 2018,
                'views'        => 390000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Mission: Impossible – Fallout',
                'description'  => 'Ethan Hunt and his IMF team, along with some familiar allies, race against time after a mission gone wrong.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/5qxePyMYDisLe8rJiBYX8HKEyv2.jpg',
                'rating'       => 8.6,
                'categories'   => json_encode(['Action', 'Thriller']),
                'release_year' => 2018,
                'views'        => 330000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Hereditary',
                'description'  => 'A grieving family is haunted by tragic and disturbing occurrences after a grandmother\'s death.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/gBsKETmfPCMSEWTWGE0ISVeMBUQ.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/lHV8HHlhwQqvhkACT7DFjnAsNMO.jpg',
                'rating'       => 8.3,
                'categories'   => json_encode(['Horror', 'Drama']),
                'release_year' => 2018,
                'views'        => 195000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Django Unchained',
                'description'  => 'A freed slave sets out to rescue his wife from a brutal plantation owner.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWAKdF.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/2oZklIzUbvZXXzIFzv7Hi8d5qws.jpg',
                'rating'       => 9.1,
                'categories'   => json_encode(['Western', 'Drama']),
                'release_year' => 2012,
                'views'        => 370000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'The Grand Budapest Hotel',
                'description'  => 'A legendary concierge and his protégé become embroiled in theft and murder.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/iJQIbOPm81fPEGKt5BPuZmfnA54.jpg',
                'rating'       => 8.7,
                'categories'   => json_encode(['Comedy', 'Drama']),
                'release_year' => 2014,
                'views'        => 220000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Knives Out',
                'description'  => 'A detective investigates the death of a patriarch of a wealthy and dysfunctional family.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/mY7SeH4HFFxW1hiI6cWuwCRKptN.jpg',
                'rating'       => 8.7,
                'categories'   => json_encode(['Mystery', 'Comedy']),
                'release_year' => 2019,
                'views'        => 285000,
                'is_trending'  => false,
            ],
            [
                'title'        => '1917',
                'description'  => 'Two soldiers are sent on a dangerous mission to deliver a message that could save 1,600 men.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYFLCCrMi9.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/dMnBBB4KNBnvFQi1V0eLBnIFpWp.jpg',
                'rating'       => 8.9,
                'categories'   => json_encode(['War', 'Drama']),
                'release_year' => 2019,
                'views'        => 255000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'The Revenant',
                'description'  => 'A frontiersman on a fur trading expedition fights for survival after being mauled by a bear.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/ji3ecJphATlVgZhVxLWEdJ0RQnl.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
                'rating'       => 8.6,
                'categories'   => json_encode(['Adventure', 'Drama']),
                'release_year' => 2015,
                'views'        => 270000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Arrival',
                'description'  => 'A linguist is recruited to communicate with alien lifeforms after they arrive on Earth.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/zjqInUwn9HHgo7CUsPEbqubLXqB.jpg',
                'rating'       => 8.8,
                'categories'   => json_encode(['Sci-Fi', 'Drama']),
                'release_year' => 2016,
                'views'        => 305000,
                'is_trending'  => false,
            ],
            [
                'title'        => 'Dunkirk',
                'description'  => 'Allied soldiers are surrounded by the German Army and must evacuate from the beaches of Dunkirk.',
                'poster_url'   => 'https://image.tmdb.org/t/p/w500/ebSnODDg9lbsMIaWg2uAbjn7TO5.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/w1280/fudEG8s6lfQwFJfjtmggLDYRCDI.jpg',
                'rating'       => 8.7,
                'categories'   => json_encode(['War', 'Action']),
                'release_year' => 2017,
                'views'        => 260000,
                'is_trending'  => false,
            ],
        ];

        foreach ($movies as $movie) {
            Movie::create($movie);
        }
    }
}